artifacts:
  type_a_z:
    path: ${base.model_dir}/type_a_z.file
    type: model

stages:
  collect_data:
    cmd: 
    - mkdir -p ${base.data_dir}/${base.division}/raw
    - python ${base.ml_dir}/src/collect_data.py --chunk z --params pipelines/type_a/z/params.yaml
    wdir: ../../../
    params:
      - pipelines/type_a/z/params.yaml:
        - base
    deps:
      - ${base.ml_dir}/src/collect_data.py
    outs:
      - ${base.data_dir}/${base.division}/raw/data.csv
  
  process_data:
    cmd: python ${base.ml_dir}/src/process_data.py --chunk z --params pipelines/type_a/z/params.yaml
    wdir: ../../../
    params:
      - pipelines/type_a/z/params.yaml:
        - base
    deps:
      - ${base.ml_dir}/src/process_data.py
      - ${base.data_dir}/${base.division}/raw/data.csv
    outs:
      - ${base.data_dir}/${base.division}/processed/data.csv
  
  train:
    cmd: python ${base.ml_dir}/src/train.py --type type_a --chunk z --params pipelines/type_a/z/params.yaml
    wdir: ../../../
    params:
      - pipelines/type_a/z/params.yaml:
        - base
    deps:
      - ${base.ml_dir}/src/train.py
      - ${base.data_dir}/${base.division}/processed/data.csv
    outs:
      - ${base.model_dir}/type_a_z.file
